import {
    DashboardIcon,
    ReportIcon,
    Jobs,
    JobsUploaderIcon,
    ManagementIcon,
    UserIcon,
    CompaniesIcon,
    RolesIcon,
    SettingIcon,
    IntegrationIcon,
    UserAppliedJobIcon,
    TeamAppliedJobsIcon,
    TeamsIcon,
    CoverLetter,
} from '@icons'

export const menuItems = [
    {
        label: 'Dashboard',
        link: '/',
        svg: DashboardIcon,
        perms: ['view_dashboard', 'view_statistics'],
    },
    {
        label: 'Jobs',
        link: '#!',
        svg: ReportIcon,
        key: 'jobs',
        perms: [
            'view_applied_job',
            'view_user_applied_job',
            'view_job_uploader',
            'view_team_applied_job',
            'change_job_status',
            'upload_csv',
            'view_job_portal',
            'view_cover_letter',
            'generate_cover_letter',
        ],
        subItems: [
            {
                label: 'My Applied Jobs',
                link: '/user-applied-jobs',
                svg: UserAppliedJobIcon,
                perms: ['view_user_applied_job'],
            },
            {
                label: 'Jobs Uploader',
                link: '/jobs-uploader',
                svg: JobsUploaderIcon,
                perms: ['view_job_uploader', 'upload_csv'],
            },
            {
                label: 'Team Applied Jobs',
                link: '/team-applied-jobs',
                svg: TeamAppliedJobsIcon,
                perms: ['view_team_applied_job', 'change_job_status'],
            },
            {
                label: 'Jobs Portal',
                link: '/jobs-portal',
                svg: Jobs,
                perms: ['view_job_portal', 'apply_job'],
            },
            {
                label: 'Cover Letter',
                link: '/coverletter',
                svg: CoverLetter,
                perms: ['view_cover_letter', 'generate_cover_letter'],
            },
        ],
    },
    {
        label: 'Management',
        link: '#!',
        svg: ManagementIcon,
        key: 'management',
        perms: [
            'view_user',
            'view_role',
            'view_company',
            'view_team',
            'create_user',
            'create_role',
            'create_company',
            'create_team',
            'update_user',
            'update_role',
            'update_company',
            'update_team',
        ],
        subItems: [
            {
                label: 'Users',
                link: '/users',
                svg: UserIcon,
                perms: ['view_user', 'create_user', 'update_user'],
            },
            {
                label: 'Companies',
                link: '/companies',
                svg: CompaniesIcon,
                perms: ['view_company', 'create_company', 'update_company'],
            },
            // {
            //     label: 'Job Source Blocking',
            //     link: '/job-source-blocking',
            //     svg: CompaniesIcon,
            //     perms: ['view_company', 'create_company', 'update_company'],
            // },
            {
                label: 'Roles',
                link: '/roles',
                svg: RolesIcon,
                perms: ['view_role', 'create_role', 'update_role'],
            },
            {
                label: 'Teams',
                link: '/teams',
                svg: TeamsIcon,
                perms: ['view_team', 'create_team', 'update_team'],
            },
        ],
    },
    {
        label: 'Settings',
        link: '#!',
        svg: SettingIcon,
        key: 'settings',
        perms: ['view_integration', 'create_integration', 'update_integration'],
        subItems: [
            {
                label: 'Integrations',
                link: '/integrations',
                svg: IntegrationIcon,
                perms: ['view_integration', 'create_integration', 'update_integration'],
            },
        ],
    },
]
