# Specifies what build spec version this file is.
# This helps AWS CodePipeline parse the file correctly.
# Keep this at 0.2
version: 0.2
# We can listen for specific phases and execute commands per phase.
phases:
  install:
   commands:
      # Install NVM
      - ./nvm_script.sh
  pre_build:
    commands:
      - yum install yarn
      - yarn install
  # Now we want to actually build our React app
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist